# Generated by Django 3.2.13 on 2022-07-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
