# Generated by Django 3.2.13 on 2022-07-26 10:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
